AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test
Resources:
  SimonSaysConversation:
    FunctionName: SimonSaysConversation
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      Policies:
      - Statement:
        - Sid: SimonSaysConversationAccess
          Effect: Allow
          Action:
          - lambda:InvokeFunction
          - logs:*
          - dynamodb:GetItem
          - lex:GetSlotType
          Resource: "*"
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/conversation_lambda
  SimonSaysDeployer:
    Type: AWS::Serverless::Function
    FunctionName: SimonSaysDeployer
    Properties:
      Timeout: 600
      Policies:
        - AdministratorAccess
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/deploy_lambda
