version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket awscodepipelinetestbucketcf
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  files:
    - outputSamTemplate.yaml
